require("stuff.plugins")
require("stuff.lualine")
require("stuff.bufferline")
require("stuff.nvim-tree")
require("stuff.telescope")
require("stuff.cmp")
require("stuff.lsp")
require("stuff.nvim-tree")
